[project]
name = "freecad-mcp-use-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.11.0",
    "langchain-google-genai>=2.1.3",
    "langchain-openai>=0.3.14",
    "mcp-use>=1.2.5",
]
